# Generated by Django 5.2 on 2025-04-15 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                unique=True,
                validators=[django.core.validators.RegexValidator("^09\\d{9}$")],
            ),
        ),
    ]
