[project]
name = "giftx"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django-stubs>=5.1.3",
    "django>=5.2",
    "ruff>=0.11.4",
    "pillow>=11.1.0",
]
