# Generated by Django 5.2 on 2025-04-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcard",
            name="quantity",
        ),
        migrations.CreateModel(
            name="GiftCardCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gift_cards.giftcard",
                    ),
                ),
            ],
        ),
    ]
