# Generated by Django 5.2 on 2025-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_brandcategory_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="giftcardcategory",
            name="image",
            field=models.ImageField(upload_to="products_category/"),
        ),
    ]
