# Generated by Django 5.2 on 2025-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_giftcard_image_alter_giftcardcategory_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="logo",
        ),
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(default=None, upload_to="brands/"),
            preserve_default=False,
        ),
    ]
