# Generated by Django 5.2 on 2025-04-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_brand_logo_brand_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcard",
            name="category",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="brand",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.brand",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="GiftCardCategory",
        ),
    ]
